-- 게시판 테이블
CREATE TABLE BASIC_BOARD (
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(30),
	WRITER VARCHAR(20),
	CONTENT VARCHAR(50),
	READ_CNT INT DEFAULT 0,
	CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM BASIC_BOARD;

INSERT INTO BASIC_BOARD (TITLE, WRITER) VALUES ('제목1', '작성자1');

DROP TABLE BASIC_BOARD;

INSERT INTO BASIC_BOARD (BOARD_NUM, TITLE, WRITER, CONTENT) VALUES (1, '첫 번째 글', '김자바', '첫 번째 내용');
INSERT INTO BASIC_BOARD (BOARD_NUM, TITLE, WRITER, CONTENT) VALUES (2, '두 번째 글', '이자바', '두 번째 내용');
INSERT INTO BASIC_BOARD (BOARD_NUM, TITLE, WRITER, CONTENT) VALUES (3, '세 번째 글', '박자바', '세 번째 내용');

SELECT TITLE
FROM BASIC_BOARD
WHERE BOARD_NUM = 1;

SELECT DATABASE();
USE study_db;
SHOW TABLES;

SELECT * FROM BASIC_BOARD;