# 게시글 테이블
CREATE TABLE BOARD (
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	CONTENT TEXT NOT NULL,
	REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP(),
	READ_CNT INT DEFAULT 0
);

# 댓글 테이블
CREATE TABLE BOARD_REPLY (
	REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT,
	CONTENT VARCHAR(30) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	REG_DATE DATETIME DEFAULT SYSDATE(),
	BOARD_NUM INT NOT NULL,
	CONSTRAINT FK_BOARD_REPLY				-- 제약 조건 이름
		FOREIGN KEY (BOARD_NUM)				-- 이 컬럼이
		REFERENCES BOARD (BOARD_NUM)		-- 저 테이블의 저 컬럼들을 참조
		ON DELETE CASCADE					-- 삭제 시 연쇄 삭제
);

SELECT * FROM BOARD_REPLY;

ALTER TABLE BOARD_REPLY 
DROP FOREIGN KEY `1`;