-- 드래그 영역 실행 : ALT + X

SELECT * FROM EMP;

-- 데이터 삽입, 삭제, 수정 쿼리
-- 연습용 테이블 생성
CREATE TABLE STUDENT (
	STU_NUM INT PRIMARY KEY,
	STU_NAME VARCHAR(30) NOT NULL,
	KOR_SCORE INT,
	ENG_SCORE INT
);

SELECT * FROM STUDENT;

DROP TABLE STUDENT;

-- 데이터 삽입
-- INSERT INTO 테이블명 (컬럼명)
-- INSERT 시 모든 컬럼에 데이터를 넣을 필요는 없다. 단, 지정하지 않은 컬럼에는 NULL 데이터가 들어간다.
INSERT INTO STUDENT VALUES(1, "김자바", 80, 80);
INSERT INTO STUDENT (KOR_SCORE, ENG_SCORE, STU_NUM, STU_NAME) VALUES(90, 70, 2, "이자바");
INSERT INTO STUDENT (STU_NUM, STU_NAME) VALUES (3, "박자바");
INSERT INTO STUDENT (STU_NUM, STU_NAME) VALUES (4, "박자바");

INSERT INTO STUDENT VALUES (10, 'KIM', 70, 90);
INSERT INTO STUDENT VALUES (11, 'KIM1', 70, 90);
INSERT INTO STUDENT VALUES (12, 'KIM2', 80, 90);
INSERT INTO STUDENT VALUES (13, 'KIM3', 90, 90);
INSERT INTO STUDENT VALUES (14, 'KIM4', 100, 90);

COMMIT;
ROLLBACK;

-- 데이터 삭제 : DELETE
-- DELETE FROM 테이블명 WHERE 조건;
DELETE
FROM STUDENT;

DELETE
FROM STUDENT AS S
WHERE S.KOR_SCORE >= 90;

-- 데이터 수정 : UPDATE
-- 학번이 10번인 학생의 이름은 'AAA', 국어점수는 100점으로 변경
UPDATE STUDENT
SET 
STU_NAME = 'AAA', 
KOR_SCORE = 100
WHERE STU_NUM = 10;

SELECT * FROM STUDENT;