CREATE TABLE ITEM (
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT,
	ITEM_NAME VARCHAR(20) NOT NULL,
	ITEM_PRICE INT NOT NULL,
	REG_DATE DATETIME DEFAULT SYSDATE(),
	ITEM_INTRO VARCHAR(50)
);

SELECT * FROM ITEM;

DROP TABLE ITEM;