DROP TABLE SHOP_MEMBER;

DELETE FROM SHOP_MEMBER;

ALTER TABLE SHOP_MEMBER MODIFY MEM_PW VARCHAR(255) NULL;
ALTER TABLE SHOP_MEMBER MODIFY MEM_TEL VARCHAR(50) NULL;
ALTER TABLE SHOP_MEMBER MODIFY MEM_ADDR VARCHAR(255) NULL;
ALTER TABLE SHOP_MEMBER MODIFY ADDR_DETAIL VARCHAR(255) NULL;

SELECT * FROM SHOP_MEMBER;