-- 1.
CREATE TABLE BOOK_INFO (
	BOOK_NUM INT PRIMARY KEY ,
	BOOK_TITLE VARCHAR(50) NOT NULL ,
	BOOK_AUTHOR VARCHAR(20) NOT NULL ,
	BOOK_PRICE INT ,
	BOOK_PUBLISHER VARCHAR(20) DEFAULT '미지정' ,
	BOOK_PUBDATE DATETIME
);

-- 2.
INSERT INTO BOOK_INFO
VALUES
(101, '자바 기초', '홍길동', 30000, 'A출판', '2025-02-15'),
(102, '리액트 기초', '이순신', 20000, 'B출판', '2025-01-22');

-- 3.
UPDATE BOOK_INFO
SET
	BOOK_TITLE = '자바 고급',
	BOOK_PRICE = 25000,
	BOOK_PUBLISHER = 'IT출판'
WHERE BOOK_NUM = 101;

-- 4.
SELECT 
	E.EMPNO , 
	E.ENAME , 
	E.SAL , 
	E.COMM AS '인센티브'
FROM EMP E
WHERE (E.SAL BETWEEN 500 AND 3000)
	AND E.COMM IS NULL;

-- 5.
SELECT 
	E.EMPNO , 
	E.ENAME , 
	E.JOB , 
	E.HIREDATE 
FROM EMP E
WHERE E.ENAME LIKE '%병%' 
	OR E.ENAME LIKE '%김%'
ORDER BY E.JOB ASC, E.EMPNO DESC;

-- 6.
SELECT 
	E.EMPNO ,
	E.ENAME ,
	E.DEPTNO ,
	CASE E.DEPTNO 
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부'
	END AS '부서명'
FROM EMP E;

-- 7.
SELECT 
	E.EMPNO ,
	E.DEPTNO ,
	D.DNAME ,
	SUBSTR(E.ENAME, 2) AS '이름'
FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO 
WHERE YEAR(E.HIREDATE) BETWEEN '2003' AND '2006';

-- 8.
SELECT
	E.EMPNO ,
	E.ENAME ,
	E.SAL ,
	IFNULL(E.COMM, 0) AS COMM ,
	(E.SAL * 12 + IFNULL(E.COMM, 0)) AS TOTAL_SALARY
FROM EMP E
ORDER BY TOTAL_SALARY DESC;

-- 9.
SELECT
	E.EMPNO ,
	E.ENAME ,
	E.HIREDATE ,
	E.SAL ,
	E.DEPTNO ,
	D.DNAME 
FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME != '인사부'
	AND E.SAL >= 500
ORDER BY E.EMPNO DESC, E.ENAME ASC;

-- 10.
-- 3개