USE smartfarm;

CREATE TABLE SENSOR_DHT22 (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TEMPERATURE DECIMAL(4,1) NOT NULL,
	HUMIDITY DECIMAL(4,1) NOT NULL,
	RECORDED_AT DATETIME NOT NULL DEFAULT NOW()
);

SELECT * FROM SENSOR_DHT22;

ALTER TABLE SENSOR_DHT22 ADD COLUMN FAN_ON TINYINT(1) DEFAULT 0;

CREATE TABLE SENSOR_LIGHT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LIGHT_VALUE DECIMAL(10,2) NOT NULL,
    RECORDED_AT DATETIME NOT NULL DEFAULT NOW()
);

ALTER TABLE SENSOR_LIGHT ADD COLUMN LED_ON TINYINT(1) DEFAULT 0;

SELECT * FROM SENSOR_LIGHT;

CREATE TABLE SENSOR_AIR (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	RAW_VALUE INT NOT NULL,
	RECORDED_AT DATETIME NOT NULL DEFAULT NOW()
);

ALTER TABLE SENSOR_AIR ADD COLUMN FAN_ON TINYINT(1) DEFAULT 0;

SELECT * FROM SENSOR_AIR;

CREATE TABLE SENSOR_MOTION (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	BUZZER_ON TINYINT(1) DEFAULT 0,
	RECORDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM SENSOR_MOTION;

# 임계값 프리셋
CREATE TABLE THRESHOLD_PRESET (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	TEMP_HIGH FLOAT NOT NULL DEFAULT 30.0,
	HUM_HIGH FLOAT NOT NULL DEFAULT 70.0,
	AIR_PPM_BAD INT NOT NULL DEFAULT 500,
	LUX_HIGH INT NOT NULL DEFAULT 10000,
	LUX_LOW INT NOT NULL DEFAULT 3000,
	IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 0,
	CREATED_AT DATETIME NOT NULL DEFAULT NOW()
);

# 기본 프리셋 초기 데이터
INSERT INTO THRESHOLD_PRESET (NAME, TEMP_HIGH, HUM_HIGH, AIR_PPM_BAD, LUX_HIGH, LUX_LOW, IS_ACTIVE)
VALUES
  ('기본값', 30.0, 70.0, 500, 10000, 3000, 1),
  ('여름',   35.0, 80.0, 500, 12000, 4000, 0),
  ('겨울',   22.0, 50.0, 500,  8000, 2000, 0);

# 알림 이력
CREATE TABLE ALERT_LOG (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  SENSOR_TYPE VARCHAR(20) NOT NULL,   # 'temperature', 'humidity', 'air', 'lux'
  VALUE FLOAT NOT NULL,
  THRESHOLD FLOAT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT NOW()
);

SELECT * FROM ALERT_LOG;

CREATE TABLE MEMBER (
	MEMBER_ID INT PRIMARY KEY AUTO_INCREMENT,
	MEMBER_EMAIL VARCHAR(100) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR(255) NOT NULL,
	MEMBER_NAME VARCHAR(50) NOT NULL,
	MEMBER_PHONE VARCHAR(20) NOT NULL,
	MEMBER_BIRTH DATE NOT NULL,
	MEMBER_ADDR VARCHAR(255) NOT NULL,
	MEMBER_ADDR_DETAIL VARCHAR(255),
	MEMBER_ROLE VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',  # ROLE_USER | ROLE_MANAGER
	MEMBER_STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',  # ACTIVE | INACTIVE
	MEMBER_CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM MEMBER;

CREATE TABLE CATEGORY (
	CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NAME VARCHAR(50) NOT NULL
);

SELECT * FROM CATEGORY;

CREATE TABLE PRODUCT (
	PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_ID INT NOT NULL,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	PRODUCT_PRICE INT NOT NULL,
	PRODUCT_STOCK INT NOT NULL,
	PRODUCT_DESC TEXT,
	PRODUCT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',  # ACTIVE | INACTIVE
	PRODUCT_CREATED_AT DATETIME DEFAULT NOW(),
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID)
);

ALTER TABLE PRODUCT MODIFY COLUMN PRODUCT_STOCK INT NOT NULL DEFAULT 0;
ALTER TABLE PRODUCT MODIFY COLUMN PRODUCT_PRICE DECIMAL(10, 2) NOT NULL;

SELECT * FROM PRODUCT;

CREATE TABLE PRODUCT_IMAGE (
	IMAGE_ID INT PRIMARY KEY AUTO_INCREMENT,
	PRODUCT_ID INT NOT NULL,
	IMAGE_ORIGIN_NAME VARCHAR(255) NOT NULL,
	IMAGE_SAVED_NAME VARCHAR(255) NOT NULL,
	IMAGE_TYPE VARCHAR(10) NOT NULL,  # MAIN | DESC
	IMAGE_ORDER INT NOT NULL DEFAULT 1,  # MAIN 1번 = 썸네일
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

SELECT * FROM PRODUCT_IMAGE;

CREATE TABLE ORDERS (
	ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
	MEMBER_ID INT NOT NULL,
	ORDER_STATUS VARCHAR(20) NOT NULL DEFAULT 'READY',  # READY | PAID | SHIPPED | DONE | CANCEL
	ORDER_TOTAL_PRICE DECIMAL(10, 2) NOT NULL,
	ORDER_CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

ALTER TABLE ORDERS ADD COLUMN TOSS_ORDER_ID VARCHAR(64) UNIQUE;
ALTER TABLE ORDERS ADD COLUMN PAYMENT_KEY VARCHAR(200);

INSERT INTO ORDERS (MEMBER_ID, ORDER_STATUS, ORDER_TOTAL_PRICE, TOSS_ORDER_ID)
VALUES (6, 'READY', 1000, 'ORDER_TEST_001');
UPDATE ORDERS SET ORDER_TOTAL_PRICE = 1000, ORDER_STATUS = 'READY', TOSS_ORDER_ID = 'ORDER_TEST_012' WHERE ORDER_ID = 2;
INSERT INTO ORDERS (MEMBER_ID, ORDER_STATUS, ORDER_TOTAL_PRICE, TOSS_ORDER_ID)
VALUES (6, 'READY', 1000, 'ORDER_TEST_013');
INSERT INTO ORDERS (MEMBER_ID, ORDER_STATUS, ORDER_TOTAL_PRICE, TOSS_ORDER_ID)
VALUES (6, 'READY', 1000, 'ORDER_TEST_014');


SELECT * FROM ORDERS;

CREATE TABLE ORDER_ITEM (
	ORDER_ITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
	ORDER_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	ORDER_ITEM_QTY INT NOT NULL,
	ORDER_ITEM_PRICE DECIMAL(10, 2) NOT NULL,
	FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE DELIVERY (
	DELIVERY_ID INT PRIMARY KEY AUTO_INCREMENT,
	ORDER_ID INT NOT NULL,
	RECIPIENT_NAME VARCHAR(50) NOT NULL,
	RECIPIIENT_PHONE VARCHAR(20) NOT NULL,
	RECIPIENT_ADDRESS VARCHAR(200) NOT NULL,
	RECIPIENT_ADDRESS_DETAIL VARCHAR(100),
	DELIVERY_STATUS VARCHAR(20) DEFAULT 'READY',  -- READY | SHIPPED | DELIVERED
	DELIVERY_CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);
