SELECT * FROM SENSOR_DHT22 ORDER BY id desc;
SELECT * FROM SENSOR_LIGHT ORDER BY id desc;
SELECT * FROM SENSOR_AIR ORDER BY id desc;
SELECT * FROM SENSOR_MOTION;
SELECT * FROM THRESHOLD_PRESET;
SELECT * FROM ALERT_LOG;

DESC THRESHOLD_PRESET;

SHOW CREATE TABLE ORDERS;
SHOW CREATE TABLE ORDER_ITEM;
SHOW CREATE TABLE PRODUCT;
SHOW CREATE TABLE CATEGORY;